#!/bin/sh

# add binaries to PATH if they aren't added yet

# Why prepend instead of append?
# Prepending ensures that binaries in $HOME/.local/bin
# take precedence over system-installed binaries with
# the same name. This is useful for overriding default
# system binaries with custom versions.

# This might have originally been generated by uv

# affix colons on either side of $PATH to simplify matching
case ":${PATH}:" in
    *:"$HOME/.local/bin":*)
        ;;
    *)
        # Prepending path in case a system-installed binary needs to be overridden
        export PATH="$HOME/.local/bin:$PATH"
        ;;
esac
